config/routes.rb
Rails.application.routes.draw do
  #get 'room/index'
  devise_for :users, controllers: {registrations: 'registrations'}

  resources :properties do
    resources :reviews
  end
  resources :favorites, only: [:index, :create, :destroy]
  resources :fav_items

  resources :rooms do
    resources :messages
  end

  #get "properties/:id", to: "properties#show"
  #resources :users, only: [:show]
  get "users/:id", to: "users#show", as: "user"

  root to: 'application#index'
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    has_many :fav_items, dependent: :destroy
    belongs_to :user
    belongs_to :property

    def add_favorite(favorite)
        current_item = fav_items.find_by(favorite_id: favorite.id)
        if current_item
          current_item.increment(:quantity)
        else
          current_item = fav_items.build(favorite_id: favorite.id)
        end
        current_item
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
    
    before_action :set_cart, only:[:show, :destroy]

    def show
    end

    def new
        @favorite = Favorite.new
    end

    def create
        @favorite = Favorite.new(favorite_params)
        if @favorite.save
            redirect_to favorite_url(@favorite), notice: "Favorite was successfully created!"
        else
            render :new
        end
    end

    def index
      @favorites = current_user.favorites
    end
  
    def destroy
        #session[:cart_id]
        @favorite.destroy if @favorite.id == session[:favorite_id]
        session[:favorite_id] = nil
        redirect_to root_path, notice: 'Favorite property was successfully destroyed.' 
    end

    # def create
    #   @favorite = current_user.favorites.build(favorite_params)
  
    #   respond_to do |format|
    #     if @favorite.save
    #       format.html { redirect_to @favorite.property, notice: "Property added to favorites." }
    #       format.json { render :show, status: :created, location: @favorite }
    #     else
    #       format.html { redirect_to root_path, alert: "Failed to add property to favorites." }
    #       format.json { render json: @favorite.errors, status: :unprocessable_entity }
    #     end
    #   end
    # end

    private

    def set_cart
        @favorite = Favorite.find(params[:id])
    end


  
    def favorite_params
      #params.require(:favorite).permit(:property_id)
      params.fetch(:favorite, {})
    end

    def invalid_cart
        logger.error "Invalid Favorite property #{params[:id]}"
        redirect_to root_path, notice: "This property never belonged here!"
    end
end
  

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_form.html.erb
<%= form_with(model: favorite, remote: true) do |f| %>
  <%= f.hidden_field :property_id, value: @property.id %>
  <%= f.submit "Add to Favorites", class: "btn btn-primary" %>
<% end %>

app/views/favorites/index.html.erb
<!-- app/views/favorites/index.html.erb -->
<h1>My Favorites</h1>

<% if @favorites.any? %>
  <ul>
    <% @favorites.each do |favorite| %>
      <li>
        <%= link_to favorite.property.name, favorite.property %>
        <%= link_to "Remove from favorites", favorite_path(@favorite), method: :delete, data: { confirm: "Are you sure you want to remove this property from favorites?" } %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No properties in favorites yet.</p>
<% end %>

app/views/favorites/show.html.erb
<h1><b>Favorite property</b></h1>
<p><b>Property name: <%= @property.name%></b><p>
<p><b>City: <%= @property.city%></b></p>
<p><b>Country: <%= @property.country%></b></p>
<p><b>Price: <%= @property.price%>Rs</b></p>
<p><b>Status: <%= @property.status%></b></p>
<p><b>Year: <%= @property.year%></b></p>
<p><b>Owner: <%= @property.user.name%> </b></p>

<%if user_signed_in? and current_user.id == @property.user_id%>
    <%= button_to "Edit", edit_property_path(@property), method: :get, notice: "Property updated!"%>
    <%= button_to "Delete", property_path(@property), method: :delete%>
<%end%>