config/routes.rb
Rails.application.routes.draw do
  #get 'room/index'
  devise_for :users, controllers: {registrations: 'registrations'}

  resources :properties do
    resources :reviews
  end
  resources :favorites, only: [:index, :create, :destroy]
  resources :fav_items

  resources :rooms do
    resources :messages
  end

  #get "properties/:id", to: "properties#show"
  #resources :users, only: [:show]
  get "users/:id", to: "users#show", as: "user"

  root to: 'application#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/fav_item.rb
class FavItem < ApplicationRecord
    belongs_to :property
    belongs_to :favorite
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    has_many :fav_items, dependent: :destroy
    belongs_to :user
    belongs_to :property

    def add_favorite(favorite)
        current_item = fav_items.find_by(favorite_id: favorite.id)
        if current_item
          current_item.increment(:quantity)
        else
          current_item = fav_items.build(favorite_id: favorite.id)
        end
        current_item
    end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  after_create_commit {broadcast_append_to room}
  before_create :confirm_participant

  def confirm_participant
    return unless room.is_private

    is_participant = Participant.where(user_id: user.id, room_id: room.id).first
    throw :abort unless is_participant
  end
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/property.rb
class Property < ApplicationRecord
    belongs_to :user

    #Pagination
    #paginates_per 3


    validates :name, :price, :country, :year, presence: true
    has_many :fav_items, dependent: :destroy
    #has_many :favorites, through: :fav_items

    has_many :reviews, dependent: :destroy
    enum status: {Sale:0, Rent:1, Sold:2}
    has_many_attached :images
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :property
  belongs_to :user
  validates :body, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
    validates_uniqueness_of :name
    scope :public_rooms, -> { where(is_private: false) }
    after_create_commit { broadcast_if_public }
    has_many :messages
    has_many :participants, dependent: :destroy

    def broadcast_if_public
        broadcast_append_to 'rooms' unless is_private
    end

    def self.create_private_room(users, room_name)
        single_room = Room.create(name: room_name, is_private: true)
        users.each do |user|
            Participant.create(user_id: user.id, room_id: single_room.id)
        end
        single_room
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  
  enum role: {customer: 0, agent: 1}
  has_many :properties, dependent: :destroy
  has_many :favorites
  validates :name, presence: true
  validates_uniqueness_of :email
  scope :all_except, ->(user) { where.not(id: user) }
  after_create_commit {broadcast_append_to 'users'}
  has_many :messages

  #validates :role, inclusion: {in: role.keys}
  def favorite?(property)
    favorites.exists?(property_id: property.id)
  end

  def favorite(property)
    favorites.find_by(property_id: property.id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def create
        @property = Property.find(params[:property_id])
        @review = @property.reviews.build(review_params)
        @review.user = current_user

        if @review.save
        redirect_to @property, notice: 'Review was successfully created.'
        else
        redirect_to @property, alert: 'Failed to create the review.'
        end
    end

    # def edit
    #     @review = Review.find(params[:id])
    # end
    
    # def update
    #     @review = Review.find(params[:id])
    
    #     if @review.update(review_params)
    #       redirect_to @review
    #     else
    #       render :edit, status: :unprocessable_entity
    #     end
    # end



    def destroy
        @property = Property.find(params[:property_id])
        @review = @property.reviews.find(params[:id])
        @review.destroy
        redirect_to property_path(@property), status: :see_other
    end


    private
    def review_params
        params.require(:review).permit(:name, :body)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @room = Room.new
    @rooms = Room.public_rooms

    @users = User.all_except(current_user)
    render 'index'
  end

  def show
    @single_room = Room.find(params[:id])

    @room = Room.new
    @rooms = Room.public_rooms

    @message = Message.new
    @messages = @single_room.messages.order(created_at: :asc)

    @users = User.all_except(current_user)
    render 'index'
  end

  def create
    @room = Room.create(name: params['room']['name'])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
        @users = User.all_except(current_user)
    
        @room = Room.new
        @rooms = Room.public_rooms
        @room_name = get_name(@user, current_user)
        @single_room = Room.where(name: @room_name).first || Room.create_private_room([@user, current_user], @room_name)
    
        @message = Message.new
        @messages = @single_room.messages.order(created_at: :asc)
        render 'rooms/index'
    end
    
    private
    
    def get_name(user1, user2)
        user = [user1, user2].sort
        "private_#{user[0].id}_#{user[1].id}"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fav_items_helper.rb
module FavItemsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_new_message_form.html.erb
<div class="form-group msg-form">
  <%= form_with(model: [@single_room, @message], remote: true, class:'d-flex') do |f| %>
    <%= f.text_field :body, id: 'chat-text', class: 'form-control msg-content', autocomplete: 'off' %>
    <%= f.submit data: {disable_with: false}, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/layouts/_new_room_form.html.erb
<%= form_with(model: @room, remote: true, class:'d-flex') do |f| %>
  <%= f.text_field :name, class: 'form-control', autocomplete: 'off' %>
  <%= f.submit data: {disable_with: false} %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <style>
      <%= ".msg-#{current_user&.id}" %> {
      background-color: #007bff !important;
      padding: 10px;
      }
      <%= ".cont-#{current_user&.id}" %> {
      display: flex;
        justify-content: flex-end
      }
    </style>
  </head>

  <body>
      <div class="topnav">
        <%= link_to "LuxeLiving", root_path, class: "active" %>
        <% if user_signed_in? and current_user.role == "agent"%>
          <%= link_to "Sell", new_property_path%>
          <%= link_to "Sign Out", destroy_user_session_path, data:{turbo_method: :delete}%>
          <%= link_to "Properties", properties_path%>
          <%= link_to "Account", edit_user_registration_path%>
          <%= link_to "Community", rooms_path%>          

        <%end%>

        <% if user_signed_in? and current_user.role == "customer"%>
          <%= link_to "Sign Out", destroy_user_session_path, data:{turbo_method: :delete}%>
          <%= link_to "Properties", properties_path%>
          <%= link_to "Favorites", favorites_path%>
          <%= link_to "Account", edit_user_registration_path%>
          <%= link_to "Community", rooms_path%>          
          
        <%end%>
    </div>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>